FROM node:lts-alpine3.10 as builder

ENV PATH /app/node_modules/.bin:$PATH
ENV NODE_ENV development

WORKDIR /app

COPY ./package*.json /app/

RUN npm cache clean --force && npm install && npm audit --fix

COPY . /app

FROM nginx:mainline-alpine

COPY etc/nginx/conf.d/default.conf /etc/nginx/conf.d/

COPY --from=builder /app/dist /app/dist
