version: "3.9"
services:
  backend:
    build: ./backend
    environment:
      NODE_ENV: development
      DATABASE_URL: "file:/app/db/dev.db"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - database:/app/db

  frontend:
    build: ./frontend
    environment:
      NODE_ENV: development
      REST_API_ENTRYPOINT: /api
    volumes:
      - ./frontend:/app
      - /app/node_modules

  nginx:
    build: ./nginx
    environment:
      ENV: development
      H5BP_VERSION: 3.3.0
    ports:
      - "8080:8080"
    depends_on:
      - backend
      - frontend

  db-migration:
    image: backend
    command: npm run seed
    volumes:
      - database:/app/db
    profiles:
      - develop
    depends_on:
      - backend

volumes:
  database: {}
