version: "3.9"
services:
  backend:
    build: ./backend
    environment:
      NODE_ENV: development
    ports:
      - "5555:5555"
    volumes:
      - ./backend:/app
      - database:/app/db
    depends_on:
      - redis-cache

  frontend:
    build: ./frontend
    environment:
      NODE_ENV: development
      REST_API_ENTRYPOINT: /api
    volumes:
      - ./frontend:/app

  nginx:
    build: ./nginx
    environment:
      ENV: development
      H5BP_VERSION: 3.3.0
    ports:
      - "8080:8080"
    volumes:
      - nginx_cache:/var/cache/nginx
    depends_on:
      - backend
      - frontend
      - redis-cache

  redis-cache:
    image: redis:alpine
    volumes:
      - redis_cache:/data

volumes:
  database: {}
  nginx_cache: {}
  redis_cache: {}
