version: "3.9"
services:
  backend:
    build: ./backend
    environment:
      NODE_ENV: development
      DATABASE_URL: "file:/app/db/dev.db"
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    environment:
      NODE_ENV: development
      REST_API_ENTRYPOINT: http://127.0.0.1:8080/api
    volumes:
      - ./frontend:/app
      - /app/node_modules

  nginx:
    build: ./nginx
    environment:
      ENV: development
    ports:
      - "8080:8080"
    depends_on:
      - backend
      - frontend

volumes:
  database: {}
