version: "3.9"
services:
  backend:
    build: ../backend
    volumes:
      - ../backend:/app
      - database:/app/db
      - node_modules_backend:/app/node_modules
  frontend:
    build: ../frontend
    volumes:
      - ../frontend:/app
      - node_modules_frontend:/app/node_modules
  nginx:
    image: "nginx:mainline-alpine"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../nginx/mime.types:/etc/nginx/mime.types
      - ../nginx/backend-devel.conf:/etc/nginx/conf.d/backend.conf
      - ../nginx/frontend-devel.conf:/etc/nginx/conf.d/frontend.conf
      - ../nginx/h5bp:/etc/nginx/h5bp
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - backend
      - frontend
volumes:
  database: {}
  node_modules_backend: {}
  node_modules_frontend: {}
